name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./LibraryManagementSystem.sln
        
      - name: Build
        run: dotnet build ./LibraryManagementSystem.sln -configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./LibraryManagementSystem.API/LibraryManagementSystem.API.csproj --configuration Release --no-build
