name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  Publish:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          include-prerelease: true
          
      - name: Restore
        run: dotnet restore ./LibraryManagementSystem.sln
        
      - name: Build
        run: dotnet build ./LibraryManagementSystem.API/LibraryManagementSystem.API.csproj -configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./LibraryManagementSystem.API/LibraryManagementSystem.API.csproj --configuration Release --no-build
